"""
NumPy reference port of EQdyna's tpv1053d (friclaw=5, rate-and-state with
strong rate weakening + thermal pressurization) time loop. Elastic kernels
duplicated verbatim from port.py/port_rsf.py (rule 1: tpv8/tpv104 ports stay
untouched). Only `faulting`+`thermop` differ from port_rsf.py.

UPDATE (post fric_tp_h fix, f21afaf, master): the fric_tp_h=0.0 latent bug
this module originally reproduced (a bare module-level scalar in
globalvar.f90, never assigned in src/*.f90, confirmed empirically by
compiling a minimal program linking only globalvar.f90 and printing it --
see pathway_forward.md item 12 for the finding this port surfaced) is now
FIXED on master: `updateThermalPressurization.f90` (renamed from
thermop.f90) reads the per-node `fric(FRIC_SLOT_TP_H,i,ift)` = `fric(40)`
(0-indexed `fric[:,39]`) instead of the disconnected global. This module
now reproduces the FIXED semantics -- `fric_tp_h` is `fric[:, 39]`, a
per-node array, broadcast over the history-array time dimension -- not the
old h=0.0 behavior. Re-verified against a freshly regenerated serial
oracle from the fixed binary (not the stale pre-fix one) -- see
README-parity.md's Update 6 for the before/after parity numbers.

d9a50fa thetaPcTmp fix: confirmed present in this worktree's faulting.f90
(`git log --oneline -- src/faulting.f90` shows d9a50fa; `grep` confirms the
`thetaPcTmp = thetaPc0` initializer is in NewtonRaphson). The serial oracle
for this phase was generated by this exact worktree's binary, so oracle and
port are provably from the same fixed code -- no risk of porting fixed
semantics against a stale, pre-fix golden reference.

friclaw==5 deltas from port_rsf.py's friclaw==4 path (all traced from
faulting.f90, not guessed):
  - tnrm offset: += fric(51) (TP pore pressure), not fric(6).
  - taoc_old (pre-Newton) = fric(4) [cohesion] - xmu_pre*tnrm (tnrm already
    clamped <=0 by this point, so the Fortran's `MIN(nsdTractionVector(1),0)`
    inside NewtonRaphson is a no-op given the same clamp already applied
    upstream -- not a divergence, just written with MIN literally to match
    the source's own (redundant) guard).
  - theta_pc (fric 23) is NOT evolved for friclaw==5: NewtonRaphson's
    friclaw==5 branch never calls rate_state_normal_stress inside the loop,
    and the pre-loop call's mutation is (as in port_rsf.py) fully discarded
    -- so fric(23) is simply left untouched here.
  - Post-loop creeping-rate floor, `if(TPV==105 .and. v_trial<fric(46))
    v_trial=fric(46)`, IS exercised here (TPV=105) -- unlike tpv104
    (TPV=104), where port_rsf.py's port of the same line was a documented
    no-op. Applied AFTER extracting state_out/thetaPc_out from the Newton
    loop -- the clamp only touches v_trial, matching the Fortran's order
    (state0/thetaPc0 are assigned from the loop's last iteration BEFORE the
    clamp line runs, so they are not re-derived from the clamped v_trial).

thermop's per-node history integral (fric(51)=pore pressure, fric(52)=
temperature) reads onFaultTPHist(1,i,j,ift)=sliprate and (2,i,j,ift)=shear
traction for j=1..nt-1 (only PAST steps -- current step's slip
rate/traction aren't computed yet when thermop runs, since driver.f90
calls thermop BEFORE faulting each step). Preallocated here as
(nftnd, nsteps) arrays -- see the module-level note on memory scaling
at the bottom of this file for the full-term implication.
"""
import numpy as np
from loading import load, region_damp  # noqa: F401
import kernels_numpy


def rsf_slip_law(V2, psi, a, b, Dc, f0, V0, fw, Vw, dt):
    tmpc = 1.0 / (2.0 * V0) * np.exp(psi / a)
    tmp = (V2 + 1.0e-30) * tmpc
    xmu = a * np.log(tmp + np.sqrt(tmp ** 2 + 1.0))
    dxmudv = a * tmpc / np.sqrt(1.0 + tmp ** 2)
    fLV = f0 - (b - a) * np.log(V2 / V0)
    fss = fw + (fLV - fw) / ((1.0 + (V2 / Vw) ** 8) ** 0.125)
    fssa = fss / a
    psiss = a * np.log(2.0 * V0 / V2 * (np.exp(fssa) - np.exp(-fssa)) / 2.0)
    psi_new = psiss + (psi - psiss) * np.exp(-V2 * dt / Dc)
    return xmu, dxmudv, psi_new


def run(S, nsteps=None, verbose=True):
    dt = S['dt']; rdampk = S['rdampk']
    eq_ids = S['eq_ids']
    nsteps = nsteps or S['nstep']

    inv = kernels_numpy.build(S)
    v1, velArr, dispArr, force, stress_i, s_p = kernels_numpy.init_state(
        inv, inv['E_int'].shape[0], inv['E_pml'].shape[0])
    mass_full = np.concatenate(([1.0], S['nodalMassArr']))
    inv_mass_full = np.where(mass_full > 0, 1.0 / np.where(mass_full > 0, mass_full, 1.0), 0.0)

    nftnd = S['nftnd']; nsmp1 = S['nsmp1']; nsmp2 = S['nsmp2']
    un = S['un']; us = S['us']; ud = S['ud']; arn = S['arn']
    fric = S['fric_init'].copy()
    fnft = np.full(nftnd, 99999.0)
    timeElapsed = 0.0
    slipRateThres = S['slipRateThres']; C_elastic = S['C_elastic']
    idxF_s = [eq_ids[nsmp1, d] for d in range(3)]
    idxF_m = [eq_ids[nsmp2, d] for d in range(3)]
    massSlave = S['fnms'][nsmp1]; massMaster = S['fnms'][nsmp2]
    mr = massMaster * massSlave / (massMaster + massSlave)

    xsource, ysource, zsource = S['xsource'], S['ysource'], S['zsource']
    nucR, nucT, nucdtau0, TPV = S['nucR'], S['nucT'], S['nucdtau0'], S['TPV']
    nsmp1_coor = S['meshCoor'][nsmp1]
    radius = np.sqrt((nsmp1_coor[:, 0] - xsource) ** 2 + (nsmp1_coor[:, 1] - ysource) ** 2 +
                      (nsmp1_coor[:, 2] - zsource) ** 2)

    # thermop-specific: per-node constants (read-only, never mutated in the time loop).
    gama = fric[:, 18] / fric[:, 17]   # fric(19)/fric(18) = tp_lambda/tp_rouc
    omega = fric[:, 15]                # fric(16) = tp_a_hy
    kapa = fric[:, 16]                 # fric(17) = tp_a_th
    rouc = fric[:, 17]                 # fric(18) = tp_rouc
    Tini = fric[:, 40]                 # fric(41) = tp_Tini
    fric_tp_h = fric[:, 39].copy()  # fric(40) = FRIC_SLOT_TP_H, per-node (post f21afaf fix)

    sliprate_hist = np.zeros((nftnd, nsteps))
    shear_hist = np.zeros((nftnd, nsteps))

    def rsf_normal_stress(V2, theta_pc, tnrm, L):
        theta_pc_dot = -V2 / L * (theta_pc - np.abs(tnrm))
        return theta_pc + theta_pc_dot * dt

    for nt in range(1, nsteps + 1):
        timeElapsed += dt

        v1, velArr, dispArr, force, stress_i, s_p = kernels_numpy.elastic_step(
            inv, v1, velArr, dispArr, force, stress_i, s_p, dt, rdampk)

        # ---- thermop (friclaw==5, BEFORE faulting; uses history through nt-1) ----
        jj = nt - 1  # number of past-step history entries available (0 at nt=1)
        if jj > 0:
            j_idx = np.arange(jj)
            age = (nt - (j_idx + 1)) * dt  # (nt-j)*dt for j=1..nt-1, 0-indexed j_idx=j-1
            denom_k = 4.0 * kapa[:, None] * age[None, :] + 2.0 * (fric_tp_h ** 2)[:, None]
            denom_o = 4.0 * omega[:, None] * age[None, :] + 2.0 * (fric_tp_h ** 2)[:, None]
            ker1 = (-kapa[:, None] / (omega - kapa)[:, None] / np.sqrt(denom_k)
                    + omega[:, None] / (omega - kapa)[:, None] / np.sqrt(denom_o))
            hist_term = np.abs(shear_hist[:, :jj]) * sliprate_hist[:, :jj]
            patnode = (hist_term * ker1 * dt).sum(axis=1) * gama / np.sqrt(np.pi)
            ker2 = 1.0 / np.sqrt(denom_k)
            Tatnode = (hist_term * ker2 * dt).sum(axis=1) / rouc / np.sqrt(np.pi)
        else:
            patnode = np.zeros(nftnd); Tatnode = np.zeros(nftnd)
        fric[:, 50] = patnode
        fric[:, 51] = Tatnode + Tini

        # ---- faulting: getNsdSlipSliprateTraction (shared prelude) ----
        fx_s = force[idxF_s[0]]; fy_s = force[idxF_s[1]]; fz_s = force[idxF_s[2]]
        fx_m = force[idxF_m[0]]; fy_m = force[idxF_m[1]]; fz_m = force[idxF_m[2]]
        vx_s, vy_s, vz_s = velArr[nsmp1, 0], velArr[nsmp1, 1], velArr[nsmp1, 2]
        vx_m, vy_m, vz_m = velArr[nsmp2, 0], velArr[nsmp2, 1], velArr[nsmp2, 2]
        dx_s, dy_s, dz_s = dispArr[nsmp1, 0], dispArr[nsmp1, 1], dispArr[nsmp1, 2]
        dx_m, dy_m, dz_m = dispArr[nsmp2, 0], dispArr[nsmp2, 1], dispArr[nsmp2, 2]

        def rot(vx, vy, vz, dirvec):
            return vx * dirvec[:, 0] + vy * dirvec[:, 1] + vz * dirvec[:, 2]

        fN_s, fS_s, fD_s = rot(fx_s, fy_s, fz_s, un), rot(fx_s, fy_s, fz_s, us), rot(fx_s, fy_s, fz_s, ud)
        fN_m, fS_m, fD_m = rot(fx_m, fy_m, fz_m, un), rot(fx_m, fy_m, fz_m, us), rot(fx_m, fy_m, fz_m, ud)
        vN_s, vS_s, vD_s = rot(vx_s, vy_s, vz_s, un), rot(vx_s, vy_s, vz_s, us), rot(vx_s, vy_s, vz_s, ud)
        vN_m, vS_m, vD_m = rot(vx_m, vy_m, vz_m, un), rot(vx_m, vy_m, vz_m, us), rot(vx_m, vy_m, vz_m, ud)
        dN_s, dS_s, dD_s = rot(dx_s, dy_s, dz_s, un), rot(dx_s, dy_s, dz_s, us), rot(dx_s, dy_s, dz_s, ud)
        dN_m, dS_m, dD_m = rot(dx_m, dy_m, dz_m, un), rot(dx_m, dy_m, dz_m, us), rot(dx_m, dy_m, dz_m, ud)

        slipN0 = dN_m - dN_s; slipS0 = dS_m - dS_s; slipD0 = dD_m - dD_s
        srN0 = vN_m - vN_s; srS0 = vS_m - vS_s; srD0 = vD_m - vD_s
        srMag_full = np.sqrt(srN0 ** 2 + srS0 ** 2 + srD0 ** 2)

        fric[:, 70] = slipS0; fric[:, 71] = slipD0; fric[:, 72] = slipN0
        fric[:, 73] = srS0; fric[:, 74] = srD0
        fric[:, 75] = np.maximum(fric[:, 75], srMag_full)
        fric[:, 76] = fric[:, 76] + srMag_full * dt

        totalMass = (massSlave + massMaster) * arn
        Tn = (massSlave * massMaster * ((vN_m - vN_s) + (dN_m - dN_s) / dt) / dt
              + massSlave * fN_m - massMaster * fN_s) / totalMass + fric[:, 6] * C_elastic
        Ts = (massSlave * massMaster * (vS_m - vS_s) / dt + massSlave * fS_m - massMaster * fS_s) / totalMass \
             + fric[:, 7] * C_elastic
        Td = (massSlave * massMaster * (vD_m - vD_s) / dt + massSlave * fD_m - massMaster * fD_s) / totalMass \
             + fric[:, 48] * C_elastic

        # ---- rsfNucleation (TPV==105 matches too) ----
        F = np.where(radius < nucR, np.exp(radius ** 2 / (radius ** 2 - nucR ** 2)), 0.0)
        G = np.where(timeElapsed <= nucT,
                     np.exp((timeElapsed - nucT) ** 2 / (timeElapsed * (timeElapsed - 2.0 * nucT))), 1.0)
        dtau_nuc = nucdtau0 * F * G if (TPV == 104 or TPV == 105) else 0.0 * F
        Ts = Ts + dtau_nuc

        # ---- solveRSF (friclaw==5) ----
        tnrm = Tn + fric[:, 50]  # friclaw==5 -> += fric(51), the TP pore pressure
        tnrm = np.where(tnrm > 0.0, 0.0, tnrm)

        slipN = slipN0 + fric[:, 24] * timeElapsed
        srN = srN0 + fric[:, 24]; srS = srS0 + fric[:, 25]; srD = srD0 + fric[:, 26]
        srMag_sd = np.sqrt(srS ** 2 + srD ** 2)

        v_trial = srMag_sd
        a = fric[:, 8]; b = fric[:, 9]; Dc = fric[:, 10]; V0 = fric[:, 11]; f0 = fric[:, 12]
        fw = fric[:, 13]; Vw = fric[:, 14]
        state0 = fric[:, 19].copy()
        xmu_pre, _, _ = rsf_slip_law(v_trial, state0, a, b, Dc, f0, V0, fw, Vw, dt)
        taoc_old = fric[:, 3] - xmu_pre * np.minimum(tnrm, 0.0)  # friclaw==5: fric(4) - xmu*MIN(tnrm,0)

        T_coeff = arn * dt / mr
        trialS = Ts - taoc_old * 0.5 * (srS / v_trial) + fric[:, 25] / T_coeff
        trialD = Td - taoc_old * 0.5 * (srD / v_trial) + fric[:, 26] / T_coeff
        trialMag = np.sqrt(trialS ** 2 + trialD ** 2)

        # ---- NewtonRaphson, friclaw==5: theta_pc frozen, taoc from cohesion-MIN(tnrm,0) ----
        done = np.zeros_like(v_trial, dtype=bool)
        state_out = state0.copy(); taoc_new = np.zeros_like(v_trial)
        for _ in range(20):
            xmu, dxmudv, state_this = rsf_slip_law(v_trial, state0, a, b, Dc, f0, V0, fw, Vw, dt)
            taoc_this = fric[:, 3] - xmu * np.minimum(tnrm, 0.0)
            rsfeq = v_trial + T_coeff * (taoc_this * 0.5 - trialMag)
            drsfeqdv = 1.0 + T_coeff * (-dxmudv * np.minimum(tnrm, 0.0)) * 0.5
            exit_now = (np.abs(rsfeq / drsfeqdv) < 1.0e-14 * np.abs(v_trial)) & \
                       (np.abs(rsfeq) < 1.0e-6 * np.abs(v_trial)) & (~done)
            done_after = done | exit_now
            newSliprate = v_trial - rsfeq / drsfeqdv
            v_next = np.where(newSliprate <= 0.0, v_trial / 2.0, newSliprate)
            v_trial = np.where(done_after, v_trial, v_next)
            state_out = state_this; taoc_new = taoc_this
            done = done_after

        # post-loop creeping-rate floor: exercised here (TPV==105), unlike tpv104.
        creep_rate = fric[:, 45]  # fric(46)
        v_trial = np.where((TPV == 105) & (v_trial < creep_rate), creep_rate, v_trial)

        fric[:, 19] = state_out  # fric(23)/thetaPc NOT written -- not evolved for friclaw==5

        Ts = taoc_old * 0.5 * (srS / srMag_sd) + taoc_new * 0.5 * (trialS / trialMag)
        Td = taoc_old * 0.5 * (srD / srMag_sd) + taoc_new * 0.5 * (trialD / trialMag)

        fric[:, 77] = tnrm; fric[:, 78] = Ts; fric[:, 79] = Td
        fric[:, 46] = v_trial
        fric[:, 47] = np.sqrt(Ts ** 2 + Td ** 2)
        sliprate_hist[:, nt - 1] = fric[:, 46]
        shear_hist[:, nt - 1] = fric[:, 47]

        accN = -srN / dt - slipN / dt / dt
        accS = (v_trial * (trialS / trialMag) - srS) / dt
        accD = (v_trial * (trialD / trialMag) - srD) / dt
        xAcc = accN * un[:, 0] + accS * us[:, 0] + accD * ud[:, 0]
        yAcc = accN * un[:, 1] + accS * us[:, 1] + accD * ud[:, 1]
        zAcc = accN * un[:, 2] + accS * us[:, 2] + accD * ud[:, 2]
        xR = fx_s + fx_m; yR = fy_s + fy_m; zR = fz_s + fz_m

        force[idxF_s[0]] = (-xAcc + xR / massMaster) * mr
        force[idxF_s[1]] = (-yAcc + yR / massMaster) * mr
        force[idxF_s[2]] = (-zAcc + zR / massMaster) * mr
        force[idxF_m[0]] = (xAcc + xR / massSlave) * mr
        force[idxF_m[1]] = (yAcc + yR / massSlave) * mr
        force[idxF_m[2]] = (zAcc + zR / massSlave) * mr

        fric[:, 30] = vx_m + (xAcc + xR / massSlave) * dt
        fric[:, 31] = vy_m + (yAcc + yR / massSlave) * dt
        fric[:, 32] = vz_m + (zAcc + zR / massSlave) * dt
        fric[:, 33] = vx_s + (-xAcc + xR / massMaster) * dt
        fric[:, 34] = vy_s + (-yAcc + yR / massMaster) * dt
        fric[:, 35] = vz_s + (-zAcc + zR / massMaster) * dt

        force[0] = 0.0

        need = fnft > 5000.0
        fnft = np.where(need & (srMag_sd >= slipRateThres), timeElapsed, fnft)

        force[1:] = force[1:] * inv_mass_full[1:]
        if verbose and nt % 5 == 0:
            print('step', nt, '/', nsteps, 'max slip rate', v_trial.max())

    return dict(velArr=velArr, dispArr=dispArr, fnft=fnft, fric=fric, force=force)

# ---- Note on history-array memory scaling (for the future full port) ----
# onFaultTPHist in the Fortran is allocated ONCE, up front, at
# (2, nftmx, nstep, ntotft) -- for this case (nftnd=4005, nstep=120) that's
# 2*4005*120*8 bytes = ~7.7 MB, trivial. But it scales as O(nftnd*nstep):
# a production run with nftnd~50,000 (a large fault) and nstep~200,000 (a
# multi-second rupture at dx~50m) would need 2*50,000*200,000*8 bytes =
# ~160 GB just for this one history array -- clearly untenable to
# preallocate. The Fortran's own O(nftnd*nstep^2) compute cost (the inner
# j=1..nt-1 sum, repeated every step) would ALSO become the dominant cost
# at that scale, not just memory. A real full port for large TP cases needs
# either (a) a bounded-lookback approximation (the kernel decays as
# 1/sqrt(age), so truncating the sum to the most recent K steps once
# age >> a few thermal/hydraulic diffusion times is a defensible, testable
# approximation -- but it changes the algorithm and must be validated
# against the exact sum, not assumed), or (b) an online recursive update of
# the diffusion integral (a numerically stable "sum of decaying modes"
# formulation), neither of which exists in the current Fortran and neither
# of which was implemented in this spike -- flagging both as open work, not
# something to invent silently now.
