#! /usr/bin/env python3
"""
Script to plot on fault initials like friction and stresses.
"""
from user_defined_params import par
import matplotlib.pyplot as plt
import numpy as np
import os
from matplotlib import animation, rc

#
SMALL_SIZE = 6

# Read in file name from terminal.
# fname = input("Enter the file name : ")


def plot_initials():
  fig = plt.figure(figsize=(30,16), dpi=300, facecolor='w', edgecolor='w')
  plt.rc('font', size=SMALL_SIZE)

  ax11 = fig.add_subplot(431)
  plt.contourf(par.on_fault_vars[:,:,1])
  ax = plt.gca()
  ax.set_aspect('equal')
  plt.colorbar()
  plt.title("SW_fs")
  
  ax11 = fig.add_subplot(432)
  plt.contourf(par.on_fault_vars[:,:,2])
  ax = plt.gca()
  ax.set_aspect('equal')
  plt.colorbar()
  plt.title("SW_sd")
  
  ax11 = fig.add_subplot(433)
  plt.contourf(par.on_fault_vars[:,:,3])
  ax = plt.gca()
  ax.set_aspect('equal')
  plt.colorbar()
  plt.title("SW_D0")
  
  ax11 = fig.add_subplot(434)
  plt.contourf(par.on_fault_vars[:,:,9])
  ax = plt.gca()
  ax.set_aspect('equal')
  plt.colorbar()
  plt.title("RSF_a")
  
  ax11 = fig.add_subplot(435)
  plt.contourf(par.on_fault_vars[:,:,9])
  ax = plt.gca()
  ax.set_aspect('equal')
  plt.colorbar()
  plt.title("RSF_a")

  ax11 = fig.add_subplot(436)
  plt.contourf(par.on_fault_vars[:,:,10])
  ax = plt.gca()
  ax.set_aspect('equal')
  plt.colorbar()
  plt.title("RSF_b")
  
  ax11 = fig.add_subplot(437)
  plt.contourf(par.on_fault_vars[:,:,11])
  ax = plt.gca()
  ax.set_aspect('equal')
  plt.colorbar()
  plt.title("RSF_Dc")

  ax11 = fig.add_subplot(438)
  plt.contourf(par.on_fault_vars[:,:,46])  
  ax = plt.gca()
  ax.set_aspect('equal')
  plt.colorbar()
  plt.title("Initial slip rate")

  ax11 = fig.add_subplot(439)
  plt.contourf(par.on_fault_vars[:,:,7])  
  ax = plt.gca()
  ax.set_aspect('equal')
  plt.colorbar()
  plt.title("Initial normal")
  
  ax11 = fig.add_subplot(4, 3, 10)
  plt.contourf(par.on_fault_vars[:,:,8])  
  ax = plt.gca()
  ax.set_aspect('equal')
  plt.colorbar()
  plt.title("Initial strike shear")

  ax11 = fig.add_subplot(4, 3, 11)
  plt.contourf(par.on_fault_vars[:,:,49])  
  ax = plt.gca()
  ax.set_aspect('equal')
  plt.colorbar()
  plt.title("Initial dip shear")
  
  plt.savefig("cInitials.png", dpi = 600)
  plt.close()
  
  return (fig,)


#dirFiles = os.listdir(os.getcwd())
def _main_func(description):
    plot_initials()

if __name__ == "__main__":
    _main_func(__doc__)
