#! /usr/bin/env python3
"""
Script to plot on fault variables.
"""

import argparse
import xarray as xr
import matplotlib.pyplot as plt
import numpy as np
import os
from pdf2image import convert_from_path
from user_defined_params import *
from lib import tryint, alphanum_key, sort_nicely, generate_gif, seek_numbers_filename

#
SMALL_SIZE = 6
r = 10e6 # half range to show stresses in Pa.
mn = init_norm # initial normal stress
ms = -mn*fric_rsf_r0 # initial mean shear stress for plotting.
md = 0 # initial mean shear dip stress
# Read in file name from terminal.
# fname = input("Enter the file name : ")


def plot_fault(fname, with_state=False):
  a = xr.open_dataset(fname)
  #print (a)
  shear_strike = a.shear_strike
  shear_dip = a.shear_dip
  norm = a.effective_normal
  slip_rate = a.slip_rate + 1e-30

  ncols = 3 if with_state else 2
  figsize = (18,6) if with_state else None
  fig1 = plt.figure(figsize=figsize)
  plt.rc('font', size=SMALL_SIZE)

  ax11 = fig1.add_subplot(2,ncols,1)
  shear_strike.plot(vmin=ms-r, vmax=ms+r, extend = 'both')
  ax11.set_xlabel('')
  #ax11.set_ylabel('')

  ax12 = fig1.add_subplot(2,ncols,2)
  shear_dip.plot(vmin=md-r, vmax=md+r, extend = 'both')
  ax12.set_xlabel('')
  ax12.set_ylabel('')

  if with_state:
    ax13 = fig1.add_subplot(2,ncols,3)
    norm.plot(vmin=mn-r, vmax = mn+r, extend = 'both')

    ax21 = fig1.add_subplot(2,ncols,4)
    log10_slip_rate = np.log10(slip_rate)
    log10_slip_rate.plot(vmin=-20, vmax=2, extend = 'both')

    state = a.state_variable
    state2 = a.state_normal

    ax22 = fig1.add_subplot(2,ncols,5)
    state2.plot(vmin=-mn-r, vmax=-mn+r, extend = 'both' )
    ax22.set_ylabel('')

    ax23 = fig1.add_subplot(2,ncols,6)
    state.plot()
    ax23.set_ylabel('')
  else:
    ax21 = fig1.add_subplot(2,ncols,3)
    norm.plot(vmin=mn-r, vmax = mn+r, extend = 'both')
    #ax21.set_ylabel('')

    ax22 = fig1.add_subplot(2,ncols,4)
    log10_slip_rate = np.log10(slip_rate)
    #log10_slip_rate.rename(name_dict = {"slip_rate":"log10(slip_rate)"})
    log10_slip_rate.plot(vmin=-20, vmax=2, extend = 'both')
    ax22.set_ylabel('')

  plt.savefig(fname + ".png", dpi = 600)
  plt.close()

  return (fig1,)

def plot_roughness(fname):
  a = xr.open_dataset(fname)
  #print (a)

  b1 = a.peak
  b2 = a.pypx
  b3 = a.pypz

  fig1 = plt.figure()
  plt.rc('font', size=SMALL_SIZE)

  ax11 = fig1.add_subplot(2,2,1)
  b1.plot()
  ax11.set_xlabel('')
  #ax11.set_ylabel('')

  ax12 = fig1.add_subplot(2,2,2)
  b2.plot()
  ax12.set_xlabel('')
  ax12.set_ylabel('')

  ax21 = fig1.add_subplot(2,2,3)
  b3.plot()
  #ax21.set_ylabel('')

  plt.savefig(fname + ".png", dpi = 600)
  plt.close()

  return (fig1,)

#dirFiles = os.listdir(os.getcwd())
def _main_func(description):
    parser = argparse.ArgumentParser(description=description)
    parser.add_argument('--with-state', action='store_true',
                         help='also plot state_variable/state_normal panels '
                              '(3x2 grid instead of 2x2)')
    args = parser.parse_args()

    dirFiles = list()
    for fname in os.listdir(os.getcwd()):
        name, file_extension = os.path.splitext(fname)
        if 'fault.' in name and '.nc' in file_extension:
            dirFiles += fname
            if os.path.exists(fname + '.png') == False: plot_fault(str(fname), with_state=args.with_state)
        if 'roughness' in name and '.nc' in file_extension:
            dirFiles += fname
            plot_roughness(str(fname))
    generate_gif()

if __name__ == "__main__":
    _main_func(__doc__)

#print(*dirFiles)
#sorted_file_list = sorted(dirFiles, key=seek_numbers_filename)
#print(sorted_file_list)

#fig = plt.figure()
#anim = animation.FuncAnimation(fig, plot_fault, frames = 1, interval = 1, blit=False)


