#!/usr/bin/env python3
"""
1. Plot on fault rupture dynamics.
2. Generate SCECRuptureTime.txt for benchmarking.
"""
import numpy as np
from math    import *
from user_defined_params import par
from os.path import exists
import matplotlib.pyplot as plt
from matplotlib import animation, rc
import netCDF4 as nc
from lib import loadFrtData
#
SMALL_SIZE = 10
font = {'family': 'serif',
        'weight': 'bold',
        'size': 10}
plt.rc('font', **font)
plt.rcParams['axes.labelweight'] = font['weight']     # Ensures bold axis labels
plt.rcParams['axes.labelsize'] = font['size']          # Ensures correct font size for xlabel/ylabel

def ruptureDynamics():
    xx, zz, rupt, rupt2d, fVarArr, magnitude = loadFrtData(par)

    levels = np.linspace(0,30,60)
    fig = plt.figure(figsize=(6,3), dpi= 300, facecolor='w', edgecolor='k')
    ax1 = plt.subplot(111)
    plt.rc('font', size=SMALL_SIZE)
    plt.contourf(xx,zz,rupt2d[:,:,1])
    cbar=plt.colorbar()
    cs=plt.contour(xx,zz,rupt2d[:,:,0], levels)
    ax1.clabel(cs, inline=True, fontsize=SMALL_SIZE - 2, fmt="%.2f", colors='w') 
    cbar.set_label('m')

    ax1.set_xlabel('Strike (km)')
    ax1.set_ylabel('Dip (km)')
    ax1.set_aspect('equal')
    plt.tight_layout()
    plt.savefig("cRuptureDynamics.png", dpi = 300)
    plt.close()

    return fVarArr

def _main_func(description):
    fVarArr = ruptureDynamics()
    print('Generating rupture dynamics figure ...')

if __name__ == "__main__":
    _main_func(__doc__)
