#! /usr/bin/env python3
"""
Source stamp of the Fortran solver -- the ONE implementation (owner-approved
2026-09-24). The makefile calls it to embed the stamp in `bin/eqdyna`; the
gates (`testsys/run.py`, `testsys/e2e/run_e2e.py`) call it to refuse a binary
built from different source. Do not reimplement it in shell or anywhere
else: two implementations drift, and a drifted stamp either refuses every
good binary or passes a stale one.

THE STAMP: sha256 over `src/fortran/*.f90` (sorted by name) followed by
`src/fortran/makefile`, each fed as `name \\0 length \\0 content`, read from
the WORKING TREE -- so an uncommitted edit counts, which is the case that
matters (a gate runs against the tree you have, not against HEAD).

WHY: on 2026-09-24 a `bin/eqdyna` built on 2026-09-22, older than
src/fortran, made test_profile_env_strict fail locally for no real reason;
a stale binary can just as easily PASS on code that no longer exists.

Usage:
    src_hash.py                      print the current tree's stamp
    src_hash.py --write-inc PATH     write the Fortran include the build uses
                                     (rewritten only when the stamp changed,
                                     so an unchanged tree does not recompile)
    src_hash.py --check BINARY       exit 0 iff BINARY carries this tree's
                                     stamp; otherwise print why and exit 1
"""
import glob
import hashlib
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FSRC = os.path.join(ROOT, 'src', 'fortran')
TAG = 'EQDYNA_SRC_STAMP='
_TAG_RE = re.compile(re.escape(TAG).encode() + rb'([0-9a-f]{64})')
REBUILD = 'rebuild with ./install-eqdyna.sh'


def stamp_files(fsrc=FSRC):
    """The stamped inputs, in hashing order. Refuses (rule 2) if there is
    nothing to hash rather than stamping an empty tree."""
    names = sorted(os.path.basename(p) for p in glob.glob(os.path.join(fsrc, '*.f90')))
    if not names:
        raise FileNotFoundError('no *.f90 under %s -- nothing to stamp' % fsrc)
    if not os.path.isfile(os.path.join(fsrc, 'makefile')):
        raise FileNotFoundError('no makefile under %s -- nothing to stamp' % fsrc)
    return names + ['makefile']


def compute(fsrc=FSRC):
    h = hashlib.sha256()
    for name in stamp_files(fsrc):
        with open(os.path.join(fsrc, name), 'rb') as fh:
            data = fh.read()
        h.update(name.encode() + b'\0' + str(len(data)).encode() + b'\0' + data)
    return h.hexdigest()


def binary_stamp(binary):
    """The stamp embedded in `binary`, or None if it carries none. Raises if
    it carries two different ones (a corrupt or concatenated file)."""
    with open(binary, 'rb') as fh:
        found = {m.decode() for m in _TAG_RE.findall(fh.read())}
    if len(found) > 1:
        raise ValueError('%s carries %d different source stamps %s'
                         % (binary, len(found), sorted(found)))
    return found.pop() if found else None


def check_binary(binary, fsrc=FSRC):
    """(ok, message). A missing binary, a binary with no stamp (built before
    stamping existed) and a mismatched stamp all refuse; there is no bypass."""
    if not os.path.isfile(binary):
        return False, '%s does not exist; build it with ./install-eqdyna.sh' % binary
    tree = compute(fsrc)
    stamp = binary_stamp(binary)
    if stamp is None:
        return False, ('%s carries no source stamp (built before stamping '
                       'existed, or by a build that skipped it); %s'
                       % (binary, REBUILD))
    if stamp != tree:
        return False, ('%s was built from different source (stamp %s, tree %s); %s'
                       % (binary, stamp[:12], tree[:12], REBUILD))
    return True, '%s source stamp %s matches the tree' % (binary, tree[:12])


def inc_text(stamp):
    # 17-char tag + 64 hex = 81. A module VARIABLE with an initialiser, not a
    # parameter: it lands in .data as a global symbol, so the full tag is
    # present in the binary for binary_stamp() to find at any -O level.
    return ("    ! GENERATED by scripts/src_hash.py at build time -- do not edit, "
            "do not commit.\n"
            "    character (len = 81) :: srcStampTag = '%s%s'\n" % (TAG, stamp))


def write_inc(path, fsrc=FSRC):
    text = inc_text(compute(fsrc))
    if os.path.isfile(path) and open(path).read() == text:
        return False
    with open(path, 'w') as fh:
        fh.write(text)
    return True


def main(argv):
    if not argv:
        print(compute())
        return 0
    if len(argv) == 2 and argv[0] == '--write-inc':
        write_inc(argv[1])
        return 0
    if len(argv) == 2 and argv[0] == '--check':
        ok, msg = check_binary(argv[1])
        print(('OK: ' if ok else 'REFUSED: ') + msg)
        return 0 if ok else 1
    print(__doc__)
    return 2


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
