#! /usr/bin/env python3
"""
`perf` testsys tier: pinned single-core Fortran-vs-NumPy-vs-JAX timing on
test.tpv8, with a provenance-stamped table and a ratio guard against a
checked-in baseline (testsys/perf/baseline.json).

The case is BUILT FRESH from case_input/test.tpv8 by this script, via the
same create.newcase + forced-serial + case.setup path the e2e sweep uses
(imported from run_e2e, not duplicated -- rule 1). It previously ran out of
testsys/parity/fixtures/, a frozen copy generated by make_fixtures.py from a
special PYDUMP=1 binary; that whole apparatus was removed with the parity
tier, and a frozen fixture had drifted from scripts/ anyway (its lib.py was
187 lines against the live 949). Building the case from the tracked compset
means perf measures the code the repo actually ships.

Every engine is pinned to the SAME single core (`taskset -c <core>`) with
every thread-pool env var this repo's dependency stack recognizes forced
to 1 -- OMP_NUM_THREADS, OPENBLAS_NUM_THREADS, MKL_NUM_THREADS, and JAX/XLA
via XLA_FLAGS. This replaces python/README-parity.md's earlier
threading-uncontrolled numbers (a shared 64-core machine at unpredictable
load, no thread pinning) with a number that is at least internally
comparable run-to-run on this same machine.

Gate: FAILS if the contemporaneous best python/fortran PER-STEP ratio
degrades by more than 1.5x versus testsys/perf/baseline.json. Per-step, not
total wall clock: see steady_state_per_step() for why the total is the wrong
quantity to gate on. Never gates on absolute seconds -- machine load moves
those far more than a 1.5x band.

If baseline.json is missing, or records a schema this script no longer
produces, THIS run creates it and does not fail (there is nothing valid to
compare against) and says so loudly, so it is not mistaken for a silent pass.
"""
import json
import os
import platform
import socket
import subprocess
import sys
import time

TESTSYS = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(os.path.dirname(TESTSYS))
sys.path.insert(0, REPO_ROOT)
sys.path.insert(0, TESTSYS)
sys.path.insert(0, os.path.dirname(TESTSYS))  # testsys/ itself, for profile_record
import perflib  # noqa: E402  (acquire_case_lock, rebuild_serial_case)
import profile_record  # noqa: E402  (append-only per-rank profile totals)

PYTHON_PKG = os.path.join(REPO_ROOT, 'src', 'python')
PERF_CASE_NAME = 'test.tpv8'
# Built fresh under testsys/perf/ rather than test/, so a perf run never
# collides with an e2e sweep's tree (they can run concurrently on this box).
PERF_CASE = os.path.join(TESTSYS, 'perf_case', PERF_CASE_NAME)
BASELINE_PATH = os.path.join(TESTSYS, 'baseline.json')
CORE = os.environ.get('PERF_CORE', '0')
DEGRADE_LIMIT = 1.5

# What a second concurrent perf run costs, printed by the refusal (item 74).
LOCK_CONSEQUENCE = [
    'A second invocation in this checkout rebuilds that SAME case directory'
    ' -- rmtree',
    'then create.newcase -- while the holder is timing out of it. The holder'
    ' does not',
    'crash cleanly: it reads a half-written case and reports SECONDS, so the'
    ' collision',
    'arrives as a perf regression or an improvement, not as an error'
    ' (rule 21a, item 74).',
    '',
    'NOT waiting. NOT rebuilding anyway. NOT falling back to a different case'
    ' directory --',
    'each of those is the silent fallback rule 2 forbids. Run your perf'
    ' measurement in',
    'its own git worktree (rule 21a), or wait for the holder above to finish.']


def pinned_env():
    env = dict(os.environ)
    env['OMP_NUM_THREADS'] = '1'
    env['OPENBLAS_NUM_THREADS'] = '1'
    env['MKL_NUM_THREADS'] = '1'
    env['NUMEXPR_NUM_THREADS'] = '1'
    env['XLA_FLAGS'] = (
        '--xla_cpu_multi_thread_eigen=false '
        f'--xla_force_host_platform_device_count=1'
    )
    env['XLA_CPU_MULTI_THREAD'] = '0'
    # jax's intra/inter-op thread pool (checked at runtime below too, not just asserted).
    env['JAX_PLATFORMS'] = 'cpu'
    return env


def require_affinity_pinned(affinity_str, core):
    """Item 91f: this gate used to print a WARNING and proceed when the
    pin did not take effect -- perf is the only red/green gate in this
    tool family, and proceeding on a failed precondition is rule 2's
    silent fallback. Pure function over the already-read affinity string,
    so it is unit-testable without a real taskset subprocess."""
    want = '[%s]' % core
    if affinity_str != want:
        raise SystemExit(
            'FAIL: affinity check did not report exactly core %s '
            '(got %r, wanted %r) -- pinning did not take effect on this '
            'system. Refusing to gate on an unpinned timing.'
            % (core, affinity_str, want))


def verify_affinity():
    """Runs a subprocess UNDER the same taskset used for the real timings and
    reports os.sched_getaffinity(0) from inside it -- proof the pin took
    effect, not an assumption."""
    r = subprocess.run(
        ['taskset', '-c', CORE, sys.executable, '-c',
         'import os; print(sorted(os.sched_getaffinity(0)))'],
        capture_output=True, text=True)
    return r.stdout.strip()


def time_fortran(nsteps):
    binary = os.path.join(REPO_ROOT, 'bin', 'eqdyna')
    if not os.path.exists(binary):
        raise SystemExit(
            f'FAIL: {binary} missing -- build it first with '
            './install-eqdyna.sh -m ubuntu. perf compares the SHIPPED binary '
            'against the shipped python package; there is no perf-specific build.')
    t0 = time.time()
    r = subprocess.run(['taskset', '-c', CORE, 'mpirun', '-np', '1', '-wdir', PERF_CASE, binary],
                        env=pinned_env(), capture_output=True, text=True)
    dt = time.time() - t0
    if r.returncode != 0:
        print(r.stdout[-2000:]); print(r.stderr[-2000:])
        raise SystemExit('FAIL: Fortran run failed under perf tier')
    return dt


def steady_state_per_step(engine, n_lo, n_hi):
    """Per-step solve cost by DIFFERENCE: (t(n_hi) - t(n_lo)) / (n_hi - n_lo).

    Why this and not t(nsteps)/nsteps. A single wall-clock number mixes a
    FIXED cost (interpreter start, case load, and for jax the XLA compile)
    with the per-step solve, and the mixture changes with the environment --
    measured on test.tpv8 at 114 steps: unpinned, fixed cost is 78% of the
    run; under this tier's single-thread pinning it is 13%, because pinning
    slows the SOLVE ~14x (13.8 ms/step -> 193 ms/step) while leaving compile
    roughly alone. A gate on the mixture therefore moves when XLA's compiler
    changes, or when the pinning changes, without the solver changing at all.
    Subtracting two runs cancels the fixed cost exactly.

    Separate processes on purpose: jax caches compiled functions in-process,
    so a second call in the same interpreter pays no compile and the
    subtraction would cancel the wrong thing (measured: 114 steps came back
    FASTER than 1 step that way).
    """
    out = {}
    for n in (n_lo, n_hi):
        wall, solve = time_python(engine, n)
        if solve is None:
            return None, None
        out[n] = solve
    per_step = (out[n_hi] - out[n_lo]) / float(n_hi - n_lo)
    # Item 91b: a non-positive per-step figure is an invalid measurement, not
    # a slow one -- raise rather than let it flow into the ratio this tool
    # gates on.
    if per_step <= 0:
        raise RuntimeError(
            'per-step by difference came out %.9f s/step for engine=%r '
            '(solve=%.3fs at n_lo=%d, solve=%.3fs at n_hi=%d). Refusing to '
            'report a non-positive per-step cost.'
            % (per_step, engine, out[n_lo], n_lo, out[n_hi], n_hi))
    fixed = out[n_lo] - n_lo * per_step
    return per_step, fixed


def time_python(engine, nsteps):
    script = (
        f"import sys; sys.path.insert(0, {PYTHON_PKG!r})\n"
        f"from eqdyna import eqdyna3d\n"
        f"import time; t0 = time.time()\n"
        f"out = eqdyna3d.run_case({PERF_CASE!r}, nsteps={nsteps}, "
        f"verbose=False, backend={engine!r})\n"
        f"print('PERF_WALL', time.time() - t0)\n"
    )
    t0 = time.time()
    r = subprocess.run(['taskset', '-c', CORE, sys.executable, '-c', script],
                        env=pinned_env(), capture_output=True, text=True)
    wall_incl_load = time.time() - t0
    if r.returncode != 0:
        print(r.stdout[-2000:]); print(r.stderr[-2000:])
        return None, None
    solve_only = None
    for line in r.stdout.splitlines():
        if line.startswith('PERF_WALL'):
            solve_only = float(line.split()[1])
    return wall_incl_load, solve_only


def provenance():
    sha = subprocess.run(['git', '-C', REPO_ROOT, 'rev-parse', '--short', 'HEAD'],
                          capture_output=True, text=True).stdout.strip() or 'unknown (uncommitted worktree)'
    load1, load5, load15 = os.getloadavg()
    compiler = subprocess.run(['mpif90', '--version'], capture_output=True, text=True).stdout.splitlines()
    compiler = compiler[0] if compiler else 'unknown'
    return dict(git_sha=sha, hostname=socket.gethostname(), platform=platform.platform(),
                load_avg=f'{load1:.2f} {load5:.2f} {load15:.2f}', compiler=compiler,
                pinned_core=CORE, timestamp=time.strftime('%Y-%m-%d %H:%M:%S'))


def build_perf_case():
    """create.newcase + forced serial + case.setup for PERF_CASE_NAME.

    Reuses the e2e sweep's builder so the case perf measures and the case the
    gate measures are constructed by ONE piece of code (rule 1). A drifting
    second copy of case setup is exactly what the deleted parity fixtures were.

    GATE 0 (item 74): the exclusive lock on the directory holding PERF_CASE,
    taken before ANYTHING is imported, created or deleted. It lives here, in
    the function that does the rmtree, rather than in main(): this function has
    a second caller -- run_tpv29_pinned_compare.py points PERF_CASE at
    perf_case_tpv29/ and calls it directly, never reaching main() -- and a lock
    placed in main() would guard one of the two callers and look like it
    guarded both. `perflib.acquire_case_lock` derives the resource from
    PERF_CASE for the same reason, so the lock follows whichever directory is
    actually about to be destroyed.

    The lock is KEPT after this returns (the fd stays open and is released
    atexit): main() then TIMES out of the directory it just built, and that is
    the whole span the item-74 collision can land in.
    """
    perflib.acquire_case_lock(PERF_CASE, LOCK_CONSEQUENCE)
    # Announced only once the lock is held: "Building ..." printed ahead of a
    # refusal describes something that never happened.
    print(f'Building a fresh {PERF_CASE_NAME} case for perf at {PERF_CASE} ...')
    return perflib.rebuild_serial_case(PERF_CASE_NAME, PERF_CASE)


def main():
    build_perf_case()

    affinity = verify_affinity()
    print(f'Pinned-core affinity check (taskset -c {CORE}): {affinity}')
    require_affinity_pinned(affinity, CORE)

    prov = provenance()

    sys.path.insert(0, PYTHON_PKG)
    from eqdyna import readInputFiles  # noqa: E402
    _params, g = readInputFiles.build_params(PERF_CASE)
    nsteps = g['nstep']

    # Two step counts, so the fixed cost can be subtracted out. n_lo is the
    # case's own step count; n_hi is 3x it, which was measured to give a
    # per-step figure reproducible to under 1% run-to-run (114 steps:
    # 7.032/7.076 s; 342 steps: 10.216/10.200 s).
    # Profile-guard/collection wiring (owner mission, 2026-09-23): PERF_CASE
    # is a fixed, reused directory, so its profile.rank0.json is captured
    # here, right after the ONE run at the case's own `nsteps` -- before the
    # next engine's run (or steady_state_per_step's n_lo/n_hi runs, further
    # below) overwrites it. term='perf-pinned-single-core' names this axis
    # explicitly; it is not one of the e2e sweep's 'gate'/'full' values and
    # must never be confused with them.
    _sha_r = subprocess.run(['git', '-C', REPO_ROOT, 'rev-parse', '--short',
                             'HEAD'], capture_output=True, text=True)
    if _sha_r.returncode != 0 or not _sha_r.stdout.strip():
        raise SystemExit('FAIL: git rev-parse --short HEAD failed (rc=%d): %s'
                         % (_sha_r.returncode, _sha_r.stderr.strip()))
    perf_sha = _sha_r.stdout.strip()

    n_lo, n_hi = nsteps, nsteps * 3
    t_fortran = time_fortran(nsteps)
    profile_record.capture_run(PERF_CASE, case=PERF_CASE_NAME,
                               backend='fortran', ranks=1,
                               term='perf-pinned-single-core', sha=perf_sha,
            tree_dirty=profile_record.ledger.tree_dirty_once())
    t_numpy_wall, t_numpy_solve = time_python('numpy', nsteps)
    if t_numpy_solve is not None:
        profile_record.capture_run(PERF_CASE, case=PERF_CASE_NAME,
                                   backend='python-numpy', ranks=1,
                                   term='perf-pinned-single-core', sha=perf_sha,
            tree_dirty=profile_record.ledger.tree_dirty_once())
    try:
        import jax  # noqa: F401
        have_jax = True
    except ImportError:
        have_jax = False
    t_jax_wall, t_jax_solve = (time_python('jax', nsteps) if have_jax else (None, None))
    if have_jax and t_jax_solve is not None:
        profile_record.capture_run(PERF_CASE, case=PERF_CASE_NAME,
                                   backend='python-jax', ranks=1,
                                   term='perf-pinned-single-core', sha=perf_sha,
            tree_dirty=profile_record.ledger.tree_dirty_once())

    print('\n==== testsys: perf -- provenance ====')
    for k, v in prov.items():
        print(f'  {k}: {v}')

    print(f'\n==== testsys: perf -- pinned single-core timing (tpv8, {nsteps} steps, core {CORE}) ====')
    print(f'  Fortran (mpirun -np 1, pinned):        {t_fortran:8.2f} s')
    if t_numpy_solve is not None:
        print(f'  NumPy   (solve-only, pinned):           {t_numpy_solve:8.2f} s  '
              f'(wall incl. interpreter/import: {t_numpy_wall:.2f} s)')
    else:
        print('  NumPy   : FAILED to run')
    if have_jax:
        if t_jax_solve is not None:
            print(f'  JAX-CPU (solve+compile, pinned, 1 thread): {t_jax_solve:8.2f} s  '
                  f'(wall incl. interpreter/import: {t_jax_wall:.2f} s)')
        else:
            print('  JAX-CPU : FAILED to run')
    else:
        print('  JAX-CPU : SKIPPED (jax not importable)')

    # ---- steady-state per-step, the quantity actually gated ----
    print(f'\n==== testsys: perf -- steady state, fixed cost subtracted '
          f'({n_lo} vs {n_hi} steps) ====')
    per_step = {}
    fortran_per_step = t_fortran / float(nsteps)
    print(f'  Fortran  {fortran_per_step * 1e3:8.1f} ms/step '
          f'(total/{nsteps}; the Fortran binary has no compile phase to subtract)')
    for engine, present in (('numpy', t_numpy_solve is not None),
                            ('jax', have_jax and t_jax_solve is not None)):
        if not present:
            continue
        ps, fixed = steady_state_per_step(engine, n_lo, n_hi)
        if ps is None:
            print(f'  {engine:8s} FAILED to produce a steady-state measurement')
            continue
        per_step[engine] = ps
        print(f'  {engine:8s} {ps * 1e3:8.1f} ms/step   '
              f'(fixed setup+compile {fixed:.2f} s = '
              f'{100.0 * fixed / (fixed + n_lo * ps):.0f}% of an {n_lo}-step run)')

    ratios = {f'{e}_over_fortran': ps / fortran_per_step
              for e, ps in per_step.items()}
    best_python_over_fortran = min(ratios.values()) if ratios else None

    print('\n  Per-step ratios (python/fortran, >1 = python slower):')
    for k, v in ratios.items():
        print(f'    {k}: {v:.3f}')

    if best_python_over_fortran is None:
        raise SystemExit('FAIL: no python engine produced a timing to gate on')

    stale = (not os.path.exists(BASELINE_PATH))
    if not stale:
        with open(BASELINE_PATH) as f:
            _b = json.load(f)
        # A baseline written before this script measured per-step cannot be
        # compared against one that does -- they are different quantities.
        # Refusing to compare is the point (rule 2): a number that looks
        # comparable and is not is worse than no number.
        stale = _b.get('metric') != 'per_step'
        if stale:
            print(f'\nNOTICE: {BASELINE_PATH} records a TOTAL-wall-clock ratio '
                  f'(from {_b.get("timestamp", "unknown")}, SHA '
                  f'{_b.get("git_sha", "unknown")}, load '
                  f'{_b.get("load_avg", "unknown")}). This run measures PER-STEP '
                  'cost with the fixed compile/setup subtracted -- a different '
                  'quantity, so the two are NOT comparable and this run does not '
                  'pretend to gate on it. Re-baselining.')
    if stale:
        baseline = dict(prov, metric='per_step', ratios=ratios,
                        per_step_seconds=per_step,
                        fortran_per_step_seconds=fortran_per_step,
                        best_python_over_fortran=best_python_over_fortran,
                         note='Per-step baseline. Committed by the reviewer, '
                              'not auto-committed by this script.')
        with open(BASELINE_PATH, 'w') as f:
            json.dump(baseline, f, indent=2)
        print(f'\nNo baseline found -- wrote {BASELINE_PATH} from this run. '
              'Re-run once more to exercise the ratio guard.')
        print('SUCCESS perf (baseline created, not gated this run)')
        return 0

    with open(BASELINE_PATH) as f:
        baseline = json.load(f)
    baseline_ratio = baseline['best_python_over_fortran']
    degradation = best_python_over_fortran / baseline_ratio
    print(f'\n  Baseline best python/fortran ratio: {baseline_ratio:.3f} '
          f'(from {baseline.get("timestamp", "unknown time")}, SHA {baseline.get("git_sha", "unknown")})')
    print(f'  This run:                            {best_python_over_fortran:.3f}')
    print(f'  Degradation factor:                  {degradation:.3f} (fail if > {DEGRADE_LIMIT})')

    if degradation > DEGRADE_LIMIT:
        print(f'FAIL perf: python/fortran ratio degraded {degradation:.2f}x vs baseline '
              f'(limit {DEGRADE_LIMIT}x)')
        return 1
    print('SUCCESS perf')
    return 0


if __name__ == '__main__':
    sys.exit(main())
