name: Automatic Testing of EQdyna

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Update package list 
      run: sudo apt-get update
      
    - name: Install dependencies
      run: |
        sudo apt-get install git vim make mpich
        sudo apt-get install libnetcdf-dev libnetcdff-dev 
        sudo apt-get install python3 python3-pip
        pip install numpy netCDF4 matplotlib xarray
        pip install --upgrade numpy 

    - name: Run tests
      run: |
        chmod -R 755 install-eqdyna.sh scripts
        ./install-eqdyna.sh -m ubuntu >> testRunLog.txt || true
        export EQDYNAROOT=$(pwd)
        PATH=$EQDYNAROOT/bin:$EQDYNAROOT/scripts:$PATH
        python3 testAll.py >> testRunLog.txt || true

    - name: Print testRunLog.txt
      run: cat testRunLog.txt    
      
    - name: Check errors in testRunLog.txt
      run: |
        if grep -qiE 'error|Error|ERROR|exception|failed|fatal|abort' testRunLog.txt; then
            exit 1
        fi
